[package]
name = "memoir"
description = "a library of self-describing parser combinators"
version = "0.1.0"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2018"

[dependencies]
nonempty = "0.2"
